<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="AddPaymentMethod.aspx.cs" Inherits="VivaBillingNewWeb.Database.AddPaymentMethod" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <asp:GridView runat="server" ID="grid" CssClass="table table-striped" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="grid_RowEditing" OnRowUpdating="grid_RowUpdating" OnRowDeleting="grid_RowDeleting" OnRowCancelingEdit="grid_RowCancelingEdit">
            <Columns>
                <asp:TemplateField HeaderText="ID">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblID" Text='<%#Eval("ID") %>'></asp:Label>
                    </ItemTemplate>
                    <%--<EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtId"  Text='<%#Eval("EmailId") %>'></asp:TextBox>
                    </EditItemTemplate>--%>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Payment Method">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblName" Text='<%#Eval("Name") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtName" Text='<%#Eval("Name") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <div class="input-group mb-3">
                        <input type="text" runat="server" class="form-control" id="PaymentMethod" />
            <div class="input-group-append">
                            <asp:Button runat="server" ID="Add" CssClass="btn btn-primary" OnClick="Add_Click" Text="Add Payment Method" />

            </div>
        </div>
        <div runat="server" id="ServerMessage"></div>
</asp:Content>

    
