<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="AddPrices.aspx.cs" Inherits="VivaBillingNewWeb.AddPrices" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
         <asp:GridView runat="server" ID="grid" CssClass="table table-striped" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="grid_RowEditing" OnRowUpdating="grid_RowUpdating" OnRowDeleting="grid_RowDeleting" OnRowCancelingEdit="grid_RowCancelingEdit" OnRowDataBound="grid_RowDataBound">
            <Columns>


                <asp:TemplateField HeaderText="ID">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblID" Text='<%#Eval("ID") %>'></asp:Label>
                    </ItemTemplate>
                    <%--<EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtId"  Text='<%#Eval("EmailId") %>'></asp:TextBox>
                    </EditItemTemplate>--%>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Product">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblProduct" ></asp:Label>
                    </ItemTemplate>
                    <%--<EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtProduct" Text='<%#Eval("Product") %>'></asp:TextBox>
                    </EditItemTemplate>--%>
                </asp:TemplateField>

                 <asp:TemplateField HeaderText="Product Type">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblProductType" ></asp:Label>
                    </ItemTemplate>
                   <%-- <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtProductType" Text='<%#Eval("ProductType") %>'></asp:TextBox>
                    </EditItemTemplate>--%>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Product Size">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblProductSize" ></asp:Label>
                    </ItemTemplate>
                   <%-- <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtProductSize" Text='<%#Eval("ProductSize") %>'></asp:TextBox>
                    </EditItemTemplate>--%>
                </asp:TemplateField>
                 <asp:TemplateField HeaderText="Counter Price">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblCounterPrice" Text='<%#Eval("CounterPrice") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtCounterPrice" Text='<%#Eval("CounterPrice") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Regular Price">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblRegularPrice" Text='<%#Eval("RegularPrice") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtRegularPrice" Text='<%#Eval("RegularPrice") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

               
            </Columns>
        </asp:GridView>






        <div class="input-group mb-3">
            <asp:DropDownList CssClass="custom-select" runat="server" ID="products" AutoPostBack="true" OnSelectedIndexChanged="products_SelectedIndexChanged">
                <asp:ListItem Value="0" Text="Select product"></asp:ListItem>
            </asp:DropDownList>
            <asp:DropDownList CssClass="custom-select"  runat="server" ID="productTypes" AutoPostBack="true" OnSelectedIndexChanged="productTypes_SelectedIndexChanged">
                <asp:ListItem Value="0" Text="Select type"></asp:ListItem>
            </asp:DropDownList>
            <asp:DropDownList CssClass="custom-select"  runat="server" ID="productSizes" OnSelectedIndexChanged="productSizes_SelectedIndexChanged">
                <asp:ListItem Value="0" Text="Select size"></asp:ListItem>
            </asp:DropDownList>
            <input type="text" class=" form-control" placeholder="Counter Price" runat="server" id="txtCounterPrice" />
            <input type="text" class=" form-control" placeholder="Regular Price"  runat="server" id="txtRegularPrice" />
            <div class="input-group-append">
                <asp:Button runat="server" CssClass="btn btn-primary   form-control" ID="Add" OnClick="Add_Click" Text="Add Price" />
            </div>
        </div>

        <div runat="server" id="ServerMessage"></div>
</asp:Content>
    
