<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="AddSize.aspx.cs" Inherits="VivaBillingNewWeb.Database.AddSize" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
         <asp:GridView runat="server" ID="grid" CssClass="table table-striped" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="grid_RowEditing" OnRowUpdating="grid_RowUpdating" OnRowDeleting="grid_RowDeleting" OnRowCancelingEdit="grid_RowCancelingEdit">
            <Columns>

                <asp:TemplateField HeaderText="ID">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblID" Text='<%#Eval("ID") %>'></asp:Label>
                    </ItemTemplate>
                    <%--<EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtId"  Text='<%#Eval("EmailId") %>'></asp:TextBox>
                    </EditItemTemplate>--%>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Size">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblSize" Text='<%#Eval("Size") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtSize" Text='<%#Eval("Size") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

              <%--  <asp:TemplateField HeaderText="Product Type">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblProductType" Text='<%#Eval("ProductType") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtProductType" Text='<%#Eval("ProductType") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Product">
                    <ItemTemplate>
                        <asp:Label runat="server" ID="lblProduct" Text='<%#Eval("Product") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtProduct" Text='<%#Eval("Product") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>--%>

            </Columns>
        </asp:GridView>
       
                   
              
                   
         

        <div class="input-group mb-3">
                      <input type="text" class="form-control" runat="server" id="size" />
            <div class="input-group-append">
                   <asp:Button runat="server" CssClass="btn btn-primary form-control" ID="Add" OnClick="Add_Click" Text="Add size" />
            </div>
        </div>
        <div runat="server" id="ServerMessage"></div>
</asp:Content>