<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="ShowCustomers.aspx.cs" Inherits="VivaBillingNewWeb.ShowCustomers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView runat="server" ID="grid" CssClass="table table-striped" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="grid_RowEditing" OnRowUpdating="grid_RowUpdating" OnRowDeleting="grid_RowDeleting" OnRowCancelingEdit="grid_RowCancelingEdit" OnRowDataBound="grid_RowDataBound">
        <Columns>
            <asp:TemplateField HeaderText="ID">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblID" Text='<%#Eval("ID") %>'></asp:Label>
                </ItemTemplate>
                <%--<EditItemTemplate>
                        <asp:TextBox runat="server" ID="txtId"  Text='<%#Eval("EmailId") %>'></asp:TextBox>
                    </EditItemTemplate>--%>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="First Name">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblFName" Text='<%#Eval("FirstName") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtFirstName" Text='<%#Eval("FirstName") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Last Name">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblLastName" Text='<%#Eval("LastName") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtLastName" Text='<%#Eval("LastName") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>




            <asp:TemplateField HeaderText="Firm Name">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblFirmName" Text='<%#Eval("FirmName") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtFirmName" Text='<%#Eval("FirmName") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Email">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblEmailId" Text='<%#Eval("EmailId") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtEmailId" Text='<%#Eval("EmailId") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Mobile Number">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblMobileNumber" Text='<%#Eval("MobileNumber") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtMobileNumber" Text='<%#Eval("MobileNumber") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Pin Code">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblPinCode" Text='<%#Eval("PinCode") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtPinCode" Text='<%#Eval("PinCode") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Flat">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblFlat" Text='<%#Eval("Flat") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtFlat" Text='<%#Eval("Flat") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Colony">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblColony" Text='<%#Eval("Colony") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtColony" Text='<%#Eval("Colony") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Landmark">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblLandmark" Text='<%#Eval("Landmark") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtLandmark" Text='<%#Eval("Landmark") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>





            <asp:TemplateField HeaderText="City">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblCity" Text='<%#Eval("City") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtCity" Text='<%#Eval("City") %>'></asp:TextBox>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Type">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblCustomerType" Text='<%#Eval("CustomerType") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="drpCustomerType">
                    </asp:DropDownList>
                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="State">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblState" Text='<%#Eval("State") %>' ></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="drpState"></asp:DropDownList>

                </EditItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Country">
                <ItemTemplate>
                    <asp:Label runat="server" ID="lblCountry" Text='<%#Eval("Country") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:DropDownList runat="server" ID="drpCountry" ></asp:DropDownList>
                </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <asp:Button runat="server" Text="Add customer" ID="btnAddCustomer" OnClick="btnAddCustomer_Click" />
    <div runat="server" id="ServerMessage"></div>
</asp:Content>
